# Generated by Django 4.2.7 on 2023-12-07 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0002_profile_username_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=55, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('purchased', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photographers.profile')),
            ],
        ),
    ]
