# Generated by Django 4.2.7 on 2023-12-06 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photographers', '0002_profile_username_alter_profile_user'),
        ('gallery', '0002_photos_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photographers.profile'),
        ),
    ]
